using System;

namespace analizador
{
	public static class Globals
	{
		enum TknType
		{
			// TOKENS COMPARACION
			TKN_IF,TKN_THEN,TKN_ELSE,TKN_FI,
			// TOKENS CICLO
			TKN_DO,TKN_UNTIL,TKN_WHILE,
			// TOKENS IO
			TKN_READ,TKN_WRITE,
			// TOKENS TIPO
			TKN_FLOAT,TKN_INT,TKN_BOOL,
			// TOKENS PROGRAM
			TKN_PROGRAM,
			// TOKENS COMPARATORS
			TKN_AND,TKN_OR,TKN_NOT,
			// TOKENS SIMBOLOS
			TKN_ADD,TKN_INUS,TKN_MULT,TKN_DIV,TKN_LESS,TKN_LESSEQ,TKN_GRT,TKN_GRTEQ,TKN_EQUALS,TKN_SEMICOLON,TKN_COMA,TKN_LPAREN,TKN_RPAREN,TKN_LBRACK,TKN_RBRACK,
			// TOKENS ESPECIALES
			TKN_ID,TKN_NUM,TKN_EOF
		}
	}
}

